language: node_js
node_js:
- '4.0'
before_script:
- npm install
script:
- npm test
env:
  matrix:
    secure: kt/l8IvV/aOmA7Qg1RSF+WZTIZlBU59FeqdaQcBZguWT4Ahexm5X9dd+y72h9dxUJdD4ekCGBGSpuvMroQjozeqSZb28u7hgpTPBzyUkxf9SBXgnmKiZOxmgMpG28sGj0n5LdUlhp/JvEESXefVkkKKxii/I7bci7KB4YpxpXDXC4JPVJ9vf8bD2LU871AN3zWCbu7qVZn31nURkuURuRyPTfKWbnPC+na0PVaXM1c88ESfBSpPlX41b4jfQHR1Sokv9F/un+VYhcanNDhck2IlegHbGIH4m57Cs3A6hWOdKdEDqXpM4vW5zNidzeKKx2+vqfGjvBuCSBenilQ1NkfYiEBFqp34ynd7V0aWAnkfTkADROQkKytcP/9bn1q2LbffHElEV5kNNB8jBY13DN41SU7cotblgySTHUbNMUBdu1A9UvwfUIFZamQ3WlaAnZBNn3UV5BE6R0HvnWGsx/xnETz7+NkRygzUlHjuSCCY1PmdJ9K2AByq4DyFrYu5dLRWKiw0MI6OlCi0n6MhD+x3vWLoxKh6wav54eATvpydvmWzra+Hg/Bkn32DTh+6/oou0UVmI6n2HggZE7tgz2X7eXPpejriIIdQ9Uv0DmQDECHpbSqhyIABc7ijgWGkaatbsacpkPFVX4DF7+/iZLG0XWkkCQdBfKlqXOyKN+cE=
notifications:
  slack:
    rooms:
      secure: JgziEix2KeyLwPCd+g/xsfL1xWfUPI+iqpVhrWP/X6vY2BDHAscymgNgKSyX633ZOLgg0aguDsSYVvssOuoypaFR8nXqS4dZmkOzeB6zA4sAOy5FqmSdXm0igcIySGsw3Th7MkELmLwo5dHA2OEVEAfEgHz2vX/Ii3bVBsaHuMNAb4+PCz5eFUbVZnOUygFqtbpo6yZXnDkvOAO+7sQa7v83BiieHULxZR+haFsRy5+y4DhQYQZHStLRi4U48C9AY1KzlYwtQdjq82ax6UteEL1dkNtZEhXu5Sen8GR027aUfMs2hFpod57NKTGcRWZyr8PTZZE5z0VuxIOyMJ2Tm401NwPG6x2xWScpgDVmto+vz05I2qug5ZZEd6v7gUnxWAQr5z25VfQSMO/yO/zBveWNWhnnXiiQhtqaNABhkiFhZ91Yw3T6k3BN/zEXZsJl1dYQnb/BwNbufkbd+22Th87w9JTy+Gf0iK071ebQ7zgZiwt6J9IoJdA5YDPTBOPV4STYDLwtQaGMBXiiBEV+XFGN5xu870pdt23CUSnBLumMb1VlCxiaM6z02JNaqimds8wjE1ApegpoV1uD4klZQA+Uc7BOBglaqHhNzp2asd6Tuq67p0lV1Ql5hY5+eb8SY0isBOnHrHCBI6nSlpr49WXa9ipnierCrlV5WluV6P8=
